export const logements = [
  {
    nom: "Villa du Rougadou",
    adresse: "327 montée du Rougadou",
    link: "/logements/rougadou",
    ville: "Noves",
    code_postal: 13550,

    personnes: 8,
    m2: 230,
    equipements: [
      "Vaisselle",
      "Lave-linge",
      "Four à micro-ondes",
      "Four",
      "Grille-pain",
      "Bouilloire",
      "Congélateur",
      "Frigo",
      " Cuisinière",
      "Cafetière Nespresso",
      "Aspirateur",
      "Fer à repasser",
      "Linge de cuisine",
      "Mixer",
      "Presse-fruits",
      "Couvertures en duvet",
    ],
    description:
      "Sur 4000 m² de terrain clos avec une vue sur les Alpilles, cette maison de style mas vous propose tout le confort et le calme dont vous avez besoin. Les 3 chambres à l'étage disposent d'un lit en 160 cm et de 2 lits en 180 cm. Toutes les décorations viennent d'être refaites. La maison se situe entre les Alpilles, le Luberon et le Mont Ventoux. Elle est à 5 km de la sortie de l'autoroute d'Avignon. Noves est un village provençal très charmant.",
    lits: 2,
    images: [
      "https://svwg0rrsfacftscb.public.blob.vercel-storage.com/villa%20du%20rougadou-61_websize-BrixqdFhRHkMWhUQHV8navK2eMPwBY.jpg",
      "https://svwg0rrsfacftscb.public.blob.vercel-storage.com/villa%20du%20rougadou-49_websize-ART56bEVFjiuEGFSwyItAxE9NN1F0b.jpg",
      "https://svwg0rrsfacftscb.public.blob.vercel-storage.com/villa%20du%20rougadou-37_websize-MdgXGvhjUdS1yLUsJlmrCN8tB9KQui.jpg",
      "https://svwg0rrsfacftscb.public.blob.vercel-storage.com/villa%20du%20rougadou-63_websize-4B2jgGA6Wh6wSkdSCO02WOc7AsraGb.jpg",
      "https://svwg0rrsfacftscb.public.blob.vercel-storage.com/villa%20du%20rougadou-28_websize-eSyW69HuDqBHkvjCQAds3UJimr9FJ1.jpg",
      "https://svwg0rrsfacftscb.public.blob.vercel-storage.com/villa%20du%20rougadou-26_websize-LspBosUIs3dXiYrbvQBE3EG2yiLIdV.jpg",
      "https://svwg0rrsfacftscb.public.blob.vercel-storage.com/villa%20du%20rougadou-10_websize-p42sV9D0tdfD5rcQKqvJb8an6BHc95.jpg",
    ],
    airbnb:
      "https://www.airbnb.fr/rooms/868871389907768338?source_impression_id=p3_1726741560_P3ghNRV88Nqtj5Y6",
    livret_accueil:
      "https://svwg0rrsfacftscb.public.blob.vercel-storage.com/livret-accueil-rougadou-oYi9ardDlyMYoREcOU0MY2cb5ro1Hf.pdf",
  },

  {
    nom: "Villa Picasso",
    adresse: "85 avenue pablo picasso",
    link: "/logements/noves",
    ville: "Noves",
    code_postal: 13550,

    personnes: 6,
    m2: 105,
    equipements: [
      "Jaccuzzi",
      "Vaisselle",
      "Lave-linge",
      "Four à micro-ondes",
      "Four",
      "Grille-pain",
      "Bouilloire",
      "Congélateur",
      "Frigo",
      "Cuisinière",
      "Cafetière Nespresso",
      "Aspirateur",
      "Fer à repasser",
      "Linge de cuisine",
      "Presse-fruits",
      "Couvertures en duvet",
    ],
    description:
      "Ce logement se situe à Noves dans un lotissement calme, il est accolé à la pinède de Noves. Dans ce magnifique petit village provençal, idéalement situé entre Alpilles, Luberon et Mont Ventoux. Cette demeure est fraîchement rénovée, disposant de 3 chambres, toutes équipées de climatisation. De plus, elle possède un jacuzzi tourné vers la nature, qui vous fera vivre des moments de détente inoubliables. Des supermarchés, gare, restaurants, et toutes sortes de commerces se trouvent à proximité.",
    lits: 3,
    images: [
      "https://svwg0rrsfacftscb.public.blob.vercel-storage.com/photo_1-yRsEB146SB5jNAHfDXlz5xCAjJHwl0.jpeg",
      "https://svwg0rrsfacftscb.public.blob.vercel-storage.com/photo_1-U594Tz1h1upVjZyHkckypmuoJnr77Q.jpeg",
      "https://svwg0rrsfacftscb.public.blob.vercel-storage.com/photo_2-oXR0Wkt3KHLDYTj4ErNdyE2HuqYN1B.jpeg",
      "https://svwg0rrsfacftscb.public.blob.vercel-storage.com/photo_2-xtIgxgXYE93Xc4sCwSawjlVWOmTOSe.jpeg",
      "https://svwg0rrsfacftscb.public.blob.vercel-storage.com/photo_3-nIhA235k7CJn530pfEMqAnhNk2LXv7.jpeg",
      "https://svwg0rrsfacftscb.public.blob.vercel-storage.com/photo_3-EmcwrrNMbUqUzdVsVa5sFRjDznUMFk.jpeg",
      "https://svwg0rrsfacftscb.public.blob.vercel-storage.com/photo_4-G33V1uv2Q1wBFzqHXLTILLh471Jsfy.jpeg",
      "https://svwg0rrsfacftscb.public.blob.vercel-storage.com/photo_4-nl6J2woOCpD7W269EkgcFFWqVKdZh5.jpeg",
      "https://svwg0rrsfacftscb.public.blob.vercel-storage.com/photo_5-L3eRtoeyZDcjbfYkNw8aRPii1WWQCf.jpeg",
      "https://svwg0rrsfacftscb.public.blob.vercel-storage.com/photo_5-ysPnVpScYcXBcyVjTfU3u12f8PdnQI.jpeg",
      "https://svwg0rrsfacftscb.public.blob.vercel-storage.com/photo_6-i7MkqXQTQH9fmi50vMZKLosz277oKf.jpeg",
      "https://svwg0rrsfacftscb.public.blob.vercel-storage.com/photo_6-t7wUfkejV6YoGCK4TsN9swZNIlS7Su.jpeg",
      "https://svwg0rrsfacftscb.public.blob.vercel-storage.com/photo_7-aXV59XfPnqHj4gTomY6Bc738sRVx1P.jpeg",
      "https://svwg0rrsfacftscb.public.blob.vercel-storage.com/photo_7-oVjafri8kNFYodYrqFDXNSYB7kl1AV.jpeg",
      "https://svwg0rrsfacftscb.public.blob.vercel-storage.com/photo_8-RVnFEOHNes0A5dgMS7JtPSARuJ5vNm.jpeg",
      "https://svwg0rrsfacftscb.public.blob.vercel-storage.com/photo_9-fXkZfjbdEQMCSqFsO57eNvkanf5xh7.jpeg",
    ],
    airbnb:
      "https://www.airbnb.fr/rooms/1194082735398502874?source_impression_id=p3_1726741492_P3PJoO-OkUFLh_GS",
    livret_accueil:
      "https://svwg0rrsfacftscb.public.blob.vercel-storage.com/livret-accueil-noves-QIhOEt4mYHd0GUOJBbZfZMLVXDCWJH.pdf",
  },
];
